development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  
cucumber:
  <<: *test

<% if Rails.env == 'production' %>
production:
  adapter: mysql
  database: <%= Configuration.db_name %>
  host: <%= Configuration.db_server %>
  username: <%= Configuration.db_username %>
  password: <%= Configuration.db_password %>
  pool: 5
  timeout: 5000
<% end %>